[tasks.setup]
run = """
hk install
"""

[tasks.check]
run = """
uv run ci/run-clangd-tidy.py -use-color \
  -source-filter='^((?!/dependencies/|/vcpkg_installed/).)*$' \
  -p='./build'
"""

[tools]
cmake = "latest"
meson = "latest"
ninja = "latest"
hk = "v2.1.0"
"pipx:clang-format" = "20.1.8"
"pipx:clangd-tidy" = "latest"
"pipx:gersemi" = "latest"
uv = "latest"
