[tasks.setup]
run = "hk install"

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"

[tools]
cmake = "latest"
meson = "latest"
ninja = "latest"
hk = "v2.1.0"
"pipx:clang-format" = "20.1.8"
"pipx:clangd" = "20.1.8"
"pipx:ruff" = "latest"
"pipx:zizmor" = "latest"
shellcheck = "latest"
shfmt = "latest"
actionlint = "latest"
"pipx:clangd-tidy" = "latest"
"pipx:gersemi" = "latest"
uv = "latest"
