; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "environment.iss"

#define MyAppName "blur"
#define MyAppVersion "2.0"
#define MyAppPublisher "tekno"
#define MyAppURL "https://f0e.github.io/blur"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D283CF94-CD1F-432D-B4BE-0516562C258B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} v{#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=.\output
OutputBaseFilename=blur-installer
SetupIconFile=.\resources\blur.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
WizardSmallImageFile=.\resources\greyblur.bmp
WizardImageFile=.\resources\greyblur.bmp
UsePreviousAppDir=yes
ChangesEnvironment=true

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "full"; Description: "Full installation (downloads TensorRT ~2GB)"
Name: "compact"; Description: "Compact installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "main"; Description: "blur (required)"; Types: full compact custom; Flags: fixed
Name: "vstrt"; Description: "NVIDIA TensorRT RIFE interpolation (~2GB download)"; Types: full

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "envPath"; Description: "Add to PATH"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\resources\blur-gui.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\resources\blur-cli.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\resources\libmpv-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\dependencies\*"; DestDir: "{app}"; Components: main; Flags: ignoreversion recursesubdirs createallsubdirs
Source: ".\redist\VC_redist.x64.exe"; DestDir: {tmp}; Flags: deleteafterinstall

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\blur-gui.exe"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\blur-gui.exe"; Tasks: desktopicon

[Run]
Filename: "{tmp}\VC_redist.x64.exe"; Parameters: "/install /passive /norestart"; StatusMsg: "Installing VC++ Redistributables..."; Check: not IsUpdateMode
Filename: "{app}\blur-gui.exe"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  UpdateMode: Boolean;
  ExistingDir: String;
  DownloadPage: TDownloadWizardPage;

function IsUpdateMode: Boolean;
begin
  Result := UpdateMode;
end;

function InitializeSetup(): Boolean;
begin
  UpdateMode := False;

  // Check for /UPDATE command line parameter
  if Pos('/UPDATE', UpperCase(GetCmdTail)) > 0 then
  begin
    UpdateMode := True;
  end;

  Result := True;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;

  if UpdateMode then
  begin
    // Skip most pages except the finish page for updates
    case PageID of
      wpWelcome, wpLicense, wpPassword, wpInfoBefore, wpUserInfo,
      wpSelectDir, wpSelectComponents, wpSelectProgramGroup,
      wpSelectTasks, wpReady, wpInfoAfter:
        Result := True;
    end;
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;

  if UpdateMode then
  begin
    // Auto-advance through pages during update
    case CurPageID of
      wpSelectDir:
        begin
          // Use existing installation directory if found
          if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}', 'InstallLocation', ExistingDir) then
          begin
            WizardForm.DirEdit.Text := ExistingDir;
          end;
        end;

      wpSelectTasks:
        begin
          // Preserve existing task selections from registry or use defaults
          // You can add logic here to remember previous selections
        end;
    end;
  end;
end;

procedure InitializeWizard;
begin
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), nil);
end;

function ExtractWith7Zip(ArchivePath, DestDir: String): Boolean;
var
  ResultCode: Integer;
  SevenZipPath: String;
begin
  SevenZipPath := ExpandConstant('{app}\vapoursynth\7z.exe');
  Result := Exec(SevenZipPath, 'x "' + ArchivePath + '" -o"' + DestDir + '" -y', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := Result and (ResultCode = 0);
end;

procedure DownloadAndInstallVsTrt;
var
  TempDir: String;
  PluginsDir: String;
  ResultCode: Integer;
begin
  TempDir := ExpandConstant('{tmp}\vstrt');
  PluginsDir := ExpandConstant('{app}\vapoursynth\vs-plugins');

  ForceDirectories(TempDir);
  ForceDirectories(PluginsDir);

  DownloadPage.Clear;
  DownloadPage.Add(
    'https://github.com/AmusementClub/vs-mlrt/releases/download/v15.16/VSTRT-Windows-x64.v15.16.7z',
    'vstrt.7z',
    ''
  );
  DownloadPage.Add(
    'https://github.com/AmusementClub/vs-mlrt/releases/download/v15.16/vsmlrt-windows-x64-tensorrt.v15.16.7z.001',
    'vsmlrt-tensorrt.7z.001',
    ''
  );
  DownloadPage.Add(
    'https://github.com/AmusementClub/vs-mlrt/releases/download/v15.16/vsmlrt-windows-x64-tensorrt.v15.16.7z.002',
    'vsmlrt-tensorrt.7z.002',
    ''
  );
  DownloadPage.Add(
    'https://github.com/AmusementClub/vs-mlrt/releases/download/external-models/rife_v4.26.7z',
    'rife_v4.26.7z',
    ''
  );

  DownloadPage.Show;
  try
    DownloadPage.Download;
  finally
    DownloadPage.Hide;
  end;

  // Extract vstrt.dll
  ExtractWith7Zip(ExpandConstant('{tmp}\vstrt.7z'), TempDir + '\vstrt');
  FileCopy(TempDir + '\vstrt\vstrt.dll', PluginsDir + '\vstrt.dll', False);

  // Extract trtexec.exe
  FileCopy(TempDir + '\vstrt\vsmlrt-cuda\trtexec.exe', ExpandConstant('{app}\ffmpeg\trtexec.exe'), False);

  // Extract tensorrt split archive (point 7z at .001)
  ExtractWith7Zip(ExpandConstant('{tmp}\vsmlrt-tensorrt.7z.001'), TempDir + '\tensorrt');
  // Copy everything from tensorrt archive into vs-plugins
  Exec(ExpandConstant('{cmd}'), '/c xcopy /E /I /Y "' + TempDir + '\tensorrt\*" "' + PluginsDir + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  // Extract rife model
  ExtractWith7Zip(ExpandConstant('{tmp}\rife_v4.26.7z'), TempDir + '\rife');
  Exec(ExpandConstant('{cmd}'), '/c xcopy /E /I /Y "' + TempDir + '\rife\rife_v2" "' + PluginsDir + '\models\rife_v2"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    if WizardIsTaskSelected('envPath') then
      EnvAddPath(ExpandConstant('{app}'));

    if WizardIsComponentSelected('vstrt') then
      DownloadAndInstallVsTrt;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    EnvRemovePath(ExpandConstant('{app}'));
end;
